<?php

declare(strict_types=1);

namespace RFM\Tests\Unit;

use RFM\Config\AppConfig;
use RFM\Http\Request;

trait TestConfigTrait
{
    private static function createConfig(
        bool $convertSpaces = true,
        string $replaceWith = '_',
        bool $transliteration = false,
        bool $lowerCase = false,
        bool $emptyFilename = false,
        array $ext = [],
        array $extBlacklist = [],
        array $extImg = ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'ico', 'webp'],
        bool $useAccessKeys = false,
        array $accessKeys = [],
        bool $deleteFiles = true,
        bool $createFolders = true,
        bool $deleteFolders = true,
        bool $uploadFiles = true,
        bool $renameFiles = true,
        bool $renameFolders = true,
        bool $duplicateFiles = true,
        bool $extractFiles = false,
        bool $copyCutFiles = true,
        bool $copyCutDirs = true,
        bool $chmodFiles = false,
        bool $chmodDirs = false,
        bool $previewTextFiles = false,
        bool $editTextFiles = false,
        bool $createTextFiles = false,
        bool $downloadFiles = true,
        bool $urlUpload = false,
        bool $imageEditorActive = true,
        bool $rememberTextFilter = false,
        int|false $copyCutMaxSize = false,
        int|false $copyCutMaxCount = false,
        array $editableTextFileExts = ['txt', 'log'],
        array $previewableTextFileExts = ['txt', 'log', 'xml', 'css'],
        array $googledocFileExts = ['doc', 'docx', 'pdf'],
        bool $googledocEnabled = true,
        string $currentPath = '',
        string $thumbsBasePath = '',
    ): AppConfig {
        return new AppConfig(
            baseUrl: 'http://localhost',
            uploadDir: '/source/',
            thumbsUploadDir: '/thumbs/',
            currentPath: $currentPath ?: __DIR__,
            thumbsBasePath: $thumbsBasePath ?: __DIR__,
            autoUpload: true,
            mimeExtensionRename: true,
            maxSizeTotal: false,
            maxSizeUpload: 10,
            filePermission: 0644,
            folderPermission: 0755,
            multipleSelection: true,
            multipleSelectionActionButton: true,
            defaultLanguage: 'en_EN',
            iconTheme: 'ico',
            showTotalSize: false,
            showFolderSize: false,
            showSortingBar: true,
            showFilterButtons: true,
            showLanguageSelection: true,
            defaultView: 0,
            ellipsisTitleAfterFirstRow: true,
            transliteration: $transliteration,
            convertSpaces: $convertSpaces,
            replaceWith: $replaceWith,
            lowerCase: $lowerCase,
            emptyFilename: $emptyFilename,
            filesWithoutExtension: false,
            addTimeToImg: false,
            imageMaxWidth: 0,
            imageMaxHeight: 0,
            imageMaxMode: 'auto',
            imageResizing: false,
            imageResizingWidth: 0,
            imageResizingHeight: 0,
            imageResizingMode: 'auto',
            imageResizingOverride: false,
            imageQualityJpeg: 90,
            imageQualityWebp: 90,
            defaultImageFormat: '',
            uploadResizeOptions: [],
            imageWatermark: false,
            imageWatermarkPosition: 'br',
            imageWatermarkPadding: 10,
            deleteFiles: $deleteFiles,
            createFolders: $createFolders,
            deleteFolders: $deleteFolders,
            uploadFiles: $uploadFiles,
            renameFiles: $renameFiles,
            renameFolders: $renameFolders,
            duplicateFiles: $duplicateFiles,
            extractFiles: $extractFiles,
            copyCutFiles: $copyCutFiles,
            copyCutDirs: $copyCutDirs,
            chmodFiles: $chmodFiles,
            chmodDirs: $chmodDirs,
            previewTextFiles: $previewTextFiles,
            editTextFiles: $editTextFiles,
            createTextFiles: $createTextFiles,
            downloadFiles: $downloadFiles,
            urlUpload: $urlUpload,
            extImg: $extImg,
            extFile: ['doc', 'docx', 'xls', 'xlsx', 'pdf'],
            extVideo: ['mov', 'mpeg', 'm4v', 'mp4', 'avi', 'mpg', 'wma', 'flv', 'webm'],
            extMusic: ['mp3', 'mpga', 'm4a', 'ac3', 'aiff', 'mid', 'ogg', 'wav'],
            extMisc: ['zip', 'rar', 'gz', 'tar'],
            ext: $ext,
            extBlacklist: $extBlacklist,
            editableTextFileExts: $editableTextFileExts,
            previewableTextFileExts: $previewableTextFileExts,
            jplayerExts: ['mp4', 'flv', 'webm', 'mp3', 'ogg', 'wav'],
            cadExts: ['dwg', 'dxf', 'svg'],
            googledocEnabled: $googledocEnabled,
            googledocFileExts: $googledocFileExts,
            copyCutMaxSize: $copyCutMaxSize,
            copyCutMaxCount: $copyCutMaxCount,
            hiddenFolders: [],
            hiddenFiles: ['config.php'],
            fileNumberLimitJs: 500,
            rememberTextFilter: $rememberTextFilter,
            imageEditorActive: $imageEditorActive,
            imageEditorPosition: 'bottom',
            svgPreview: true,
            darkMode: true,
            removeHeader: true,
            useAccessKeys: $useAccessKeys,
            accessKeys: $accessKeys,
            fixedImageCreation: false,
            fixedPathFromFilemanager: [],
            fixedImageCreationNameToPrepend: [],
            fixedImageCreationToAppend: [],
            fixedImageCreationWidth: [],
            fixedImageCreationHeight: [],
            fixedImageCreationOption: [],
            relativeImageCreation: false,
            relativePathFromCurrentPos: [],
            relativeImageCreationNameToPrepend: [],
            relativeImageCreationNameToAppend: [],
            relativeImageCreationWidth: [],
            relativeImageCreationHeight: [],
            relativeImageCreationOption: [],
        );
    }

    private static function createRequest(
        string $method = 'GET',
        string $uri = '/',
        array $get = [],
        array $post = [],
        array $cookies = [],
        array $server = [],
    ): Request {
        $defaultServer = [
            'REQUEST_METHOD' => $method,
            'REQUEST_URI' => $uri,
            'SCRIPT_NAME' => '/index.php',
        ];

        $_SERVER = array_merge($_SERVER, $defaultServer, $server);
        $_GET = $get;
        $_POST = $post;
        $_COOKIE = $cookies;

        return new Request();
    }
}
